# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b9e08b9ca2a9c19bfb56f74b0339e7db2981836731a3e5d6d3930f397788646434e1b87017526ed613ff7044132134229149559e79f1e4dc9c100be81fc5483

test:
  secret_key_base: cc20b6eb1d461f308fc4158049f99704ed55617fc7e3aed7bb6d8568f73ad1f779ab5bbd2da9876f545f59e06ccffc4210e57b2ab20e73f9113096494ec5ce50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
